name = "srijonee-catch-asur"
main = "src/worker.js"
compatibility_date = "2026-08-31"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "srijonee-game"
database_id = "8492ace4-0293-4493-be9f-b4275c538586"
